export const JOBS_FETCH_REQUEST = "jobs/fetchRequest"
export const JOBS_FETCH_SUCCESS = "jobs/fetchSuccess"
export const JOBS_FETCH_FAILED = "jobs/fetchFailed"
export const JOBS_ADD_DATA = "jobs/addData"
export const JOBS_ADD_FAILED = "jobs/addFailed"
export const JOBS_DELETE_SUCCESS = "jobs/deleteSuccess"
export const JOBS_DELETE_FAILED = "jobs/deleteFailed"

export const COMPANIES_FETCH_REQUEST = "companies/fetchRequest"
export const COMPANIES_FETCH_SUCCESS = "companies/fetchSuccess"
export const COMPANIES_FETCH_FAILED = "companies/fetchFailed"
export const COMPANIES_ADD_DATA = "companies/addData"
export const COMPANIES_ADD_FAILED = "companies/addFailed"
export const COMPANIES_DELETE_SUCCESS = "companies/deleteSuccess"
export const COMPANIES_DELETE_FAILED = "companies/deleteFailed"

export const USERS_ADD_DATA = "users/addData"
export const USERS_ADD_FAILED = "users/addFailed"
export const USERS_LOGIN_SUCCESS = "users/loginSuccess"
export const USERS_LOGIN_FAILED= "users/loginFailed"