services:
    orchestrator:
      build: ./orchestrator
      ports:
        - "80:4000"
      environment:
      - "APP_SERVICE_URL= http://app-service:4002/jobs"
      - "USER_SERVICE_URL= http://user-service:4001/users"
    app-service:
      build: ./services/app
      ports:
        - "4002:4002"
      environment:
        - NODE_ENV= production
        - DATABASE_URL:${SUPABASE_URL}
    user-service:
      build: ./services/users
      ports:
        - "4001:4001"
